# yaml-language-server: $schema=./node_modules/somod-schema/schemas/parameters/index.json

parameters:
  chat.http-api.id:
    type: string
  chat.websocket-api.id:
    type: string
  chat.enable.websocket:
    type: boolean
    default: true
  dynamodb.pitr.enable:
    type: boolean
    default: false
  chat.session.jwt.secret:
    type: string
  chat.session.force:
    type: boolean
    default: false
  chat.typeToAllowedActionsMap:
    type: object
    additionalProperties:
      type: array
      items:
        type: string
    default:
      {
        text: ["new", "edit"],
        image: ["new", "edit"],
        control: ["delete"],
        "audio-call": ["callStart", "callConnect", "callEnd"],
        "video-call": ["callStart", "callConnect", "callEnd"]
      }
  chat.sessionRequirementMap:
    type: object
    additionalProperties:
      type: object
      additionalProperties:
        enum:
          - thread
          - always
    default:
      {
        text: { new: "thread", edit: "thread" },
        image: { new: "thread", edit: "thread" }
      }
